name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Navigete to project 
      run: cd app_python/ 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r app_python/requirements.txt
        python -m pip install --upgrade Flask  # Upgrade Flask
        python -m pip install --upgrade Werkzeug  # Upgrade Werkzeug
      # This step installs project dependencies
    
    - name: Install flake8
      run: pip install flake8

    - name: Lint code
      run: flake8
      # This step runs the linter to check for code style and quality

    - name: Run tests
      run: python -m pytest
      # This step runs your tests using pytest

    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      # This step logs in to Docker Hub using provided secrets

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./app_python
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/khays-python-app:latest 
        cache-from: type=gha
        cache-to: type=gha,mode=max